[package]
name = "secretnote"
version = "0.1.0"
authors = ["Markus Bauer <markus.bauer@cispa.saarland>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.0.0-beta.3"
actix-files = "0.3.0-beta.1"
env_logger = "0.7.1"
