name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
      
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
            
    - name: Cache Node Modules
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Cache Rust Dependencies
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.OS }}-rust-
    - name: Cache RustUp Toolchains
      uses: actions/cache@v2
      with:
        path: ~/.rustup
        key: ${{ runner.os }}-rustup

    #- run: cd secretnote-fe && npm ci
    #  name: Install Frontend Dependencies
    #- run: cd secretnote-fe && npm run build
    #  name: Build Frontend
    
    - name: Install Rust Build Dependencies
      run: sudo apt-get install -y musl-tools
    - name: RustUp
      run: "rustup target add x86_64-unknown-linux-musl"
    - name: Build Server
      run: cargo build --release --target x86_64-unknown-linux-musl
    
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: |
          fe
          target/x86_64-unknown-linux-musl/release/secretnote
        retention-days: 365
