name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
      
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        
    # Caches for npm / cargo / rustup
    - name: Cache Node Modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Cache Rust Dependencies
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.OS }}-rust-
    - name: Cache RustUp Toolchains
      uses: actions/cache@v2
      with:
        path: ~/.rustup
        key: ${{ runner.os }}-rustup

    # Build frontend / Angular app
    - run: cd secretnote-fe && npm ci
      name: Install Frontend Dependencies
    - run: cd secretnote-fe && npm run build
      name: Build Frontend
    
    # Build server / Rust part
    - name: Install Rust Build Dependencies
      run: sudo apt-get install -y musl-tools gcc-mingw-w64-x86-64
    - name: RustUp
      run: rustup target add x86_64-unknown-linux-musl && rustup target add x86_64-pc-windows-gnu
    - name: Build Server (Linux/amd64)
      run: cargo build --release --target x86_64-unknown-linux-musl
    - name: Build Server (Windows/amd64)
      run: cargo build --release --target x86_64-pc-windows-gnu
      
    # Upload build results
    - run: cp target/x86_64-unknown-linux-musl/release/secretnote ./ && strip ./secretnote
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: "SecretNote for Linux amd64"
        path: |
          ./fe
          ./secretnote
        retention-days: 365
    - run: cp target/x86_64-pc-windows-gnu/release/secretnote.exe ./
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: "SecretNote for Windows x64"
        path: |
          ./fe
          ./secretnote.exe
        retention-days: 365
